# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import outfit_pb2 as outfit__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in outfit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FitAnalyzerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFitInfo = channel.unary_unary(
                '/outfit.FitAnalyzer/GetFitInfo',
                request_serializer=outfit__pb2.ItemRequest.SerializeToString,
                response_deserializer=outfit__pb2.RetailResponse.FromString,
                _registered_method=True)


class FitAnalyzerServicer:
    """Missing associated documentation comment in .proto file."""

    def GetFitInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FitAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFitInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFitInfo,
                    request_deserializer=outfit__pb2.ItemRequest.FromString,
                    response_serializer=outfit__pb2.RetailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'outfit.FitAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('outfit.FitAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FitAnalyzer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFitInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/outfit.FitAnalyzer/GetFitInfo',
            outfit__pb2.ItemRequest.SerializeToString,
            outfit__pb2.RetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
