# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: outfit.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'outfit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coutfit.proto\x12\x06outfit\"\x1e\n\x0bItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"`\n\x0eRetailResponse\x12\x14\n\x0c\x63lothes_name\x18\x01 \x01(\t\x12\x12\n\nbrand_name\x18\x02 \x01(\t\x12\x15\n\rpurchase_link\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x32N\n\x0eOutfitAnalyzer\x12<\n\rGetRetailInfo\x12\x13.outfit.ItemRequest\x1a\x16.outfit.RetailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'outfit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=24
  _globals['_ITEMREQUEST']._serialized_end=54
  _globals['_RETAILRESPONSE']._serialized_start=56
  _globals['_RETAILRESPONSE']._serialized_end=152
  _globals['_OUTFITANALYZER']._serialized_start=154
  _globals['_OUTFITANALYZER']._serialized_end=232
# @@protoc_insertion_point(module_scope)
