// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: outfit.proto
// Protobuf C++ Version: 6.33.4

#ifndef outfit_2eproto_2epb_2eh
#define outfit_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_outfit_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_outfit_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_outfit_2eproto;
}  // extern "C"
namespace outfit {
class ItemRequest;
struct ItemRequestDefaultTypeInternal;
extern ItemRequestDefaultTypeInternal _ItemRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ItemRequest_class_data_;
class RetailResponse;
struct RetailResponseDefaultTypeInternal;
extern RetailResponseDefaultTypeInternal _RetailResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RetailResponse_class_data_;
}  // namespace outfit
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace outfit {

// ===================================================================


// -------------------------------------------------------------------

class RetailResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:outfit.RetailResponse) */ {
 public:
  inline RetailResponse() : RetailResponse(nullptr) {}
  ~RetailResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RetailResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RetailResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RetailResponse(::google::protobuf::internal::ConstantInitialized);

  inline RetailResponse(const RetailResponse& from) : RetailResponse(nullptr, from) {}
  inline RetailResponse(RetailResponse&& from) noexcept
      : RetailResponse(nullptr, ::std::move(from)) {}
  inline RetailResponse& operator=(const RetailResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RetailResponse& operator=(RetailResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RetailResponse& default_instance() {
    return *reinterpret_cast<const RetailResponse*>(
        &_RetailResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RetailResponse& a, RetailResponse& b) { a.Swap(&b); }
  inline void Swap(RetailResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RetailResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RetailResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RetailResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RetailResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RetailResponse& from) { RetailResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RetailResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "outfit.RetailResponse"; }

  explicit RetailResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RetailResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RetailResponse& from);
  RetailResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RetailResponse&& from) noexcept
      : RetailResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClothesNameFieldNumber = 1,
    kBrandNameFieldNumber = 2,
    kPurchaseLinkFieldNumber = 3,
    kPriceFieldNumber = 4,
  };
  // string clothes_name = 1;
  void clear_clothes_name() ;
  const ::std::string& clothes_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_clothes_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_clothes_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_clothes_name();
  void set_allocated_clothes_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_clothes_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_clothes_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_clothes_name();

  public:
  // string brand_name = 2;
  void clear_brand_name() ;
  const ::std::string& brand_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_brand_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_brand_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_brand_name();
  void set_allocated_brand_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_brand_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_brand_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_brand_name();

  public:
  // string purchase_link = 3;
  void clear_purchase_link() ;
  const ::std::string& purchase_link() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_purchase_link(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_purchase_link();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_purchase_link();
  void set_allocated_purchase_link(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_purchase_link() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_purchase_link(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_purchase_link();

  public:
  // double price = 4;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // @@protoc_insertion_point(class_scope:outfit.RetailResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 65,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RetailResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr clothes_name_;
    ::google::protobuf::internal::ArenaStringPtr brand_name_;
    ::google::protobuf::internal::ArenaStringPtr purchase_link_;
    double price_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_outfit_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RetailResponse_class_data_;
// -------------------------------------------------------------------

class ItemRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:outfit.ItemRequest) */ {
 public:
  inline ItemRequest() : ItemRequest(nullptr) {}
  ~ItemRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ItemRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ItemRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ItemRequest(::google::protobuf::internal::ConstantInitialized);

  inline ItemRequest(const ItemRequest& from) : ItemRequest(nullptr, from) {}
  inline ItemRequest(ItemRequest&& from) noexcept
      : ItemRequest(nullptr, ::std::move(from)) {}
  inline ItemRequest& operator=(const ItemRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemRequest& operator=(ItemRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ItemRequest& default_instance() {
    return *reinterpret_cast<const ItemRequest*>(
        &_ItemRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ItemRequest& a, ItemRequest& b) { a.Swap(&b); }
  inline void Swap(ItemRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ItemRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ItemRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ItemRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ItemRequest& from) { ItemRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ItemRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "outfit.ItemRequest"; }

  explicit ItemRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ItemRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ItemRequest& from);
  ItemRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ItemRequest&& from) noexcept
      : ItemRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemIdFieldNumber = 1,
  };
  // int32 item_id = 1;
  void clear_item_id() ;
  ::int32_t item_id() const;
  void set_item_id(::int32_t value);

  private:
  ::int32_t _internal_item_id() const;
  void _internal_set_item_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:outfit.ItemRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ItemRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t item_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_outfit_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ItemRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ItemRequest

// int32 item_id = 1;
inline void ItemRequest::clear_item_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t ItemRequest::item_id() const {
  // @@protoc_insertion_point(field_get:outfit.ItemRequest.item_id)
  return _internal_item_id();
}
inline void ItemRequest::set_item_id(::int32_t value) {
  _internal_set_item_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:outfit.ItemRequest.item_id)
}
inline ::int32_t ItemRequest::_internal_item_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_id_;
}
inline void ItemRequest::_internal_set_item_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_id_ = value;
}

// -------------------------------------------------------------------

// RetailResponse

// string clothes_name = 1;
inline void RetailResponse::clear_clothes_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clothes_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RetailResponse::clothes_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:outfit.RetailResponse.clothes_name)
  return _internal_clothes_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RetailResponse::set_clothes_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.clothes_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:outfit.RetailResponse.clothes_name)
}
inline ::std::string* PROTOBUF_NONNULL RetailResponse::mutable_clothes_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_clothes_name();
  // @@protoc_insertion_point(field_mutable:outfit.RetailResponse.clothes_name)
  return _s;
}
inline const ::std::string& RetailResponse::_internal_clothes_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clothes_name_.Get();
}
inline void RetailResponse::_internal_set_clothes_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clothes_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RetailResponse::_internal_mutable_clothes_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.clothes_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RetailResponse::release_clothes_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:outfit.RetailResponse.clothes_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.clothes_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.clothes_name_.Set("", GetArena());
  }
  return released;
}
inline void RetailResponse::set_allocated_clothes_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.clothes_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.clothes_name_.IsDefault()) {
    _impl_.clothes_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:outfit.RetailResponse.clothes_name)
}

// string brand_name = 2;
inline void RetailResponse::clear_brand_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.brand_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RetailResponse::brand_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:outfit.RetailResponse.brand_name)
  return _internal_brand_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RetailResponse::set_brand_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.brand_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:outfit.RetailResponse.brand_name)
}
inline ::std::string* PROTOBUF_NONNULL RetailResponse::mutable_brand_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_brand_name();
  // @@protoc_insertion_point(field_mutable:outfit.RetailResponse.brand_name)
  return _s;
}
inline const ::std::string& RetailResponse::_internal_brand_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.brand_name_.Get();
}
inline void RetailResponse::_internal_set_brand_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.brand_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RetailResponse::_internal_mutable_brand_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.brand_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RetailResponse::release_brand_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:outfit.RetailResponse.brand_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.brand_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.brand_name_.Set("", GetArena());
  }
  return released;
}
inline void RetailResponse::set_allocated_brand_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.brand_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.brand_name_.IsDefault()) {
    _impl_.brand_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:outfit.RetailResponse.brand_name)
}

// string purchase_link = 3;
inline void RetailResponse::clear_purchase_link() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.purchase_link_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& RetailResponse::purchase_link() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:outfit.RetailResponse.purchase_link)
  return _internal_purchase_link();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RetailResponse::set_purchase_link(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.purchase_link_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:outfit.RetailResponse.purchase_link)
}
inline ::std::string* PROTOBUF_NONNULL RetailResponse::mutable_purchase_link()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_purchase_link();
  // @@protoc_insertion_point(field_mutable:outfit.RetailResponse.purchase_link)
  return _s;
}
inline const ::std::string& RetailResponse::_internal_purchase_link() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.purchase_link_.Get();
}
inline void RetailResponse::_internal_set_purchase_link(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.purchase_link_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RetailResponse::_internal_mutable_purchase_link() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.purchase_link_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RetailResponse::release_purchase_link() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:outfit.RetailResponse.purchase_link)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.purchase_link_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.purchase_link_.Set("", GetArena());
  }
  return released;
}
inline void RetailResponse::set_allocated_purchase_link(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.purchase_link_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.purchase_link_.IsDefault()) {
    _impl_.purchase_link_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:outfit.RetailResponse.purchase_link)
}

// double price = 4;
inline void RetailResponse::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double RetailResponse::price() const {
  // @@protoc_insertion_point(field_get:outfit.RetailResponse.price)
  return _internal_price();
}
inline void RetailResponse::set_price(double value) {
  _internal_set_price(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:outfit.RetailResponse.price)
}
inline double RetailResponse::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void RetailResponse::_internal_set_price(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace outfit


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // outfit_2eproto_2epb_2eh
