// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: outfit.proto

#include "outfit.pb.h"
#include "outfit.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace outfit {

static const char* FitAnalyzer_method_names[] = {
  "/outfit.FitAnalyzer/GetFitInfo",
};

std::unique_ptr< FitAnalyzer::Stub> FitAnalyzer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FitAnalyzer::Stub> stub(new FitAnalyzer::Stub(channel, options));
  return stub;
}

FitAnalyzer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetFitInfo_(FitAnalyzer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FitAnalyzer::Stub::GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::outfit::RetailResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::outfit::ItemRequest, ::outfit::RetailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFitInfo_, context, request, response);
}

void FitAnalyzer::Stub::async::GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::outfit::ItemRequest, ::outfit::RetailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFitInfo_, context, request, response, std::move(f));
}

void FitAnalyzer::Stub::async::GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFitInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>* FitAnalyzer::Stub::PrepareAsyncGetFitInfoRaw(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::outfit::RetailResponse, ::outfit::ItemRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFitInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>* FitAnalyzer::Stub::AsyncGetFitInfoRaw(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFitInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

FitAnalyzer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FitAnalyzer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FitAnalyzer::Service, ::outfit::ItemRequest, ::outfit::RetailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FitAnalyzer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::outfit::ItemRequest* req,
             ::outfit::RetailResponse* resp) {
               return service->GetFitInfo(ctx, req, resp);
             }, this)));
}

FitAnalyzer::Service::~Service() {
}

::grpc::Status FitAnalyzer::Service::GetFitInfo(::grpc::ServerContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace outfit
#include <grpcpp/ports_undef.inc>

