// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: outfit.proto
#ifndef GRPC_outfit_2eproto__INCLUDED
#define GRPC_outfit_2eproto__INCLUDED

#include "outfit.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace outfit {

class FitAnalyzer final {
 public:
  static constexpr char const* service_full_name() {
    return "outfit.FitAnalyzer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::outfit::RetailResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::outfit::RetailResponse>> AsyncGetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::outfit::RetailResponse>>(AsyncGetFitInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::outfit::RetailResponse>> PrepareAsyncGetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::outfit::RetailResponse>>(PrepareAsyncGetFitInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::outfit::RetailResponse>* AsyncGetFitInfoRaw(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::outfit::RetailResponse>* PrepareAsyncGetFitInfoRaw(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::outfit::RetailResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>> AsyncGetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>>(AsyncGetFitInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>> PrepareAsyncGetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>>(PrepareAsyncGetFitInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response, std::function<void(::grpc::Status)>) override;
      void GetFitInfo(::grpc::ClientContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>* AsyncGetFitInfoRaw(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::outfit::RetailResponse>* PrepareAsyncGetFitInfoRaw(::grpc::ClientContext* context, const ::outfit::ItemRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetFitInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetFitInfo(::grpc::ServerContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFitInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFitInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetFitInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFitInfo(::grpc::ServerContext* /*context*/, const ::outfit::ItemRequest* /*request*/, ::outfit::RetailResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFitInfo(::grpc::ServerContext* context, ::outfit::ItemRequest* request, ::grpc::ServerAsyncResponseWriter< ::outfit::RetailResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetFitInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetFitInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFitInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::outfit::ItemRequest, ::outfit::RetailResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::outfit::ItemRequest* request, ::outfit::RetailResponse* response) { return this->GetFitInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetFitInfo(
        ::grpc::MessageAllocator< ::outfit::ItemRequest, ::outfit::RetailResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::outfit::ItemRequest, ::outfit::RetailResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetFitInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFitInfo(::grpc::ServerContext* /*context*/, const ::outfit::ItemRequest* /*request*/, ::outfit::RetailResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFitInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::outfit::ItemRequest* /*request*/, ::outfit::RetailResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetFitInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetFitInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFitInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetFitInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFitInfo(::grpc::ServerContext* /*context*/, const ::outfit::ItemRequest* /*request*/, ::outfit::RetailResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFitInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFitInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetFitInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFitInfo(::grpc::ServerContext* /*context*/, const ::outfit::ItemRequest* /*request*/, ::outfit::RetailResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFitInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFitInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFitInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFitInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetFitInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFitInfo(::grpc::ServerContext* /*context*/, const ::outfit::ItemRequest* /*request*/, ::outfit::RetailResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFitInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFitInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFitInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::outfit::ItemRequest, ::outfit::RetailResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::outfit::ItemRequest, ::outfit::RetailResponse>* streamer) {
                       return this->StreamedGetFitInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFitInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFitInfo(::grpc::ServerContext* /*context*/, const ::outfit::ItemRequest* /*request*/, ::outfit::RetailResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFitInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::outfit::ItemRequest,::outfit::RetailResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetFitInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetFitInfo<Service > StreamedService;
};

}  // namespace outfit


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_outfit_2eproto__INCLUDED
