// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: outfit.proto
// Protobuf C++ Version: 6.33.4

#include "outfit.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace outfit {

inline constexpr RetailResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        clothes_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        brand_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        purchase_link_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        price_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RetailResponse::RetailResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RetailResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RetailResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RetailResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RetailResponseDefaultTypeInternal() {}
  union {
    RetailResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RetailResponseDefaultTypeInternal _RetailResponse_default_instance_;

inline constexpr ItemRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        det_obj_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ItemRequest::ItemRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ItemRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ItemRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemRequestDefaultTypeInternal() {}
  union {
    ItemRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemRequestDefaultTypeInternal _ItemRequest_default_instance_;
}  // namespace outfit
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_outfit_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_outfit_2eproto = nullptr;
const ::uint32_t
    TableStruct_outfit_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::outfit::ItemRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::outfit::ItemRequest, _impl_.det_obj_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::outfit::RetailResponse, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::outfit::RetailResponse, _impl_.clothes_name_),
        PROTOBUF_FIELD_OFFSET(::outfit::RetailResponse, _impl_.brand_name_),
        PROTOBUF_FIELD_OFFSET(::outfit::RetailResponse, _impl_.purchase_link_),
        PROTOBUF_FIELD_OFFSET(::outfit::RetailResponse, _impl_.price_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::outfit::ItemRequest)},
        {5, sizeof(::outfit::RetailResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::outfit::_ItemRequest_default_instance_._instance,
    &::outfit::_RetailResponse_default_instance_._instance,
};
const char descriptor_table_protodef_outfit_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014outfit.proto\022\006outfit\"\036\n\013ItemRequest\022\017\n"
    "\007det_obj\030\001 \001(\t\"`\n\016RetailResponse\022\024\n\014clot"
    "hes_name\030\001 \001(\t\022\022\n\nbrand_name\030\002 \001(\t\022\025\n\rpu"
    "rchase_link\030\003 \001(\t\022\r\n\005price\030\004 \001(\0012H\n\013FitA"
    "nalyzer\0229\n\nGetFitInfo\022\023.outfit.ItemReque"
    "st\032\026.outfit.RetailResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_outfit_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_outfit_2eproto = {
    false,
    false,
    234,
    descriptor_table_protodef_outfit_2eproto,
    "outfit.proto",
    &descriptor_table_outfit_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_outfit_2eproto::offsets,
    file_level_enum_descriptors_outfit_2eproto,
    file_level_service_descriptors_outfit_2eproto,
};
namespace outfit {
// ===================================================================

class ItemRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ItemRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ItemRequest, _impl_._has_bits_);
};

ItemRequest::ItemRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ItemRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:outfit.ItemRequest)
}
PROTOBUF_NDEBUG_INLINE ItemRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::outfit::ItemRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        det_obj_(arena, from.det_obj_) {}

ItemRequest::ItemRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ItemRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ItemRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ItemRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:outfit.ItemRequest)
}
PROTOBUF_NDEBUG_INLINE ItemRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        det_obj_(arena) {}

inline void ItemRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ItemRequest::~ItemRequest() {
  // @@protoc_insertion_point(destructor:outfit.ItemRequest)
  SharedDtor(*this);
}
inline void ItemRequest::SharedDtor(MessageLite& self) {
  ItemRequest& this_ = static_cast<ItemRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.det_obj_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ItemRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ItemRequest(arena);
}
constexpr auto ItemRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ItemRequest),
                                            alignof(ItemRequest));
}
constexpr auto ItemRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ItemRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ItemRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ItemRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ItemRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ItemRequest>(), &ItemRequest::ByteSizeLong,
              &ItemRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ItemRequest, _impl_._cached_size_),
          false,
      },
      &ItemRequest::kDescriptorMethods,
      &descriptor_table_outfit_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ItemRequest_class_data_ =
        ItemRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ItemRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ItemRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ItemRequest_class_data_.tc_table);
  return ItemRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2>
ItemRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ItemRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ItemRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::outfit::ItemRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string det_obj = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ItemRequest, _impl_.det_obj_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string det_obj = 1;
    {PROTOBUF_FIELD_OFFSET(ItemRequest, _impl_.det_obj_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\7\0\0\0\0\0\0"
    "outfit.ItemRequest"
    "det_obj"
  }},
};
PROTOBUF_NOINLINE void ItemRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:outfit.ItemRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.det_obj_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ItemRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ItemRequest& this_ = static_cast<const ItemRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ItemRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ItemRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:outfit.ItemRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string det_obj = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_det_obj().empty()) {
      const ::std::string& _s = this_._internal_det_obj();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "outfit.ItemRequest.det_obj");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:outfit.ItemRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ItemRequest::ByteSizeLong(const MessageLite& base) {
  const ItemRequest& this_ = static_cast<const ItemRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ItemRequest::ByteSizeLong() const {
  const ItemRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:outfit.ItemRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string det_obj = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_det_obj().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_det_obj());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ItemRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ItemRequest*>(&to_msg);
  auto& from = static_cast<const ItemRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:outfit.ItemRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_det_obj().empty()) {
      _this->_internal_set_det_obj(from._internal_det_obj());
    } else {
      if (_this->_impl_.det_obj_.IsDefault()) {
        _this->_internal_set_det_obj("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ItemRequest::CopyFrom(const ItemRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:outfit.ItemRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ItemRequest::InternalSwap(ItemRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.det_obj_, &other->_impl_.det_obj_, arena);
}

::google::protobuf::Metadata ItemRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RetailResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RetailResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_._has_bits_);
};

RetailResponse::RetailResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RetailResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:outfit.RetailResponse)
}
PROTOBUF_NDEBUG_INLINE RetailResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::outfit::RetailResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        clothes_name_(arena, from.clothes_name_),
        brand_name_(arena, from.brand_name_),
        purchase_link_(arena, from.purchase_link_) {}

RetailResponse::RetailResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RetailResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RetailResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RetailResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.price_ = from._impl_.price_;

  // @@protoc_insertion_point(copy_constructor:outfit.RetailResponse)
}
PROTOBUF_NDEBUG_INLINE RetailResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        clothes_name_(arena),
        brand_name_(arena),
        purchase_link_(arena) {}

inline void RetailResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.price_ = {};
}
RetailResponse::~RetailResponse() {
  // @@protoc_insertion_point(destructor:outfit.RetailResponse)
  SharedDtor(*this);
}
inline void RetailResponse::SharedDtor(MessageLite& self) {
  RetailResponse& this_ = static_cast<RetailResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.clothes_name_.Destroy();
  this_._impl_.brand_name_.Destroy();
  this_._impl_.purchase_link_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RetailResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RetailResponse(arena);
}
constexpr auto RetailResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RetailResponse),
                                            alignof(RetailResponse));
}
constexpr auto RetailResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RetailResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RetailResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RetailResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RetailResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RetailResponse>(), &RetailResponse::ByteSizeLong,
              &RetailResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_._cached_size_),
          false,
      },
      &RetailResponse::kDescriptorMethods,
      &descriptor_table_outfit_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RetailResponse_class_data_ =
        RetailResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RetailResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RetailResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RetailResponse_class_data_.tc_table);
  return RetailResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 65, 2>
RetailResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RetailResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::outfit::RetailResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double price = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 3, 0,
      PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.price_)}},
    // string clothes_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.clothes_name_)}},
    // string brand_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.brand_name_)}},
    // string purchase_link = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.purchase_link_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string clothes_name = 1;
    {PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.clothes_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string brand_name = 2;
    {PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.brand_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string purchase_link = 3;
    {PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.purchase_link_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double price = 4;
    {PROTOBUF_FIELD_OFFSET(RetailResponse, _impl_.price_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\25\14\12\15\0\0\0\0"
    "outfit.RetailResponse"
    "clothes_name"
    "brand_name"
    "purchase_link"
  }},
};
PROTOBUF_NOINLINE void RetailResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:outfit.RetailResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.clothes_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.brand_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.purchase_link_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.price_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RetailResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RetailResponse& this_ = static_cast<const RetailResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RetailResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RetailResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:outfit.RetailResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string clothes_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_clothes_name().empty()) {
      const ::std::string& _s = this_._internal_clothes_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "outfit.RetailResponse.clothes_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string brand_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_brand_name().empty()) {
      const ::std::string& _s = this_._internal_brand_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "outfit.RetailResponse.brand_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string purchase_link = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_purchase_link().empty()) {
      const ::std::string& _s = this_._internal_purchase_link();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "outfit.RetailResponse.purchase_link");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // double price = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this_._internal_price(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:outfit.RetailResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RetailResponse::ByteSizeLong(const MessageLite& base) {
  const RetailResponse& this_ = static_cast<const RetailResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RetailResponse::ByteSizeLong() const {
  const RetailResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:outfit.RetailResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string clothes_name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_clothes_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_clothes_name());
      }
    }
    // string brand_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_brand_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_brand_name());
      }
    }
    // string purchase_link = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_purchase_link().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_purchase_link());
      }
    }
    // double price = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RetailResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RetailResponse*>(&to_msg);
  auto& from = static_cast<const RetailResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:outfit.RetailResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_clothes_name().empty()) {
        _this->_internal_set_clothes_name(from._internal_clothes_name());
      } else {
        if (_this->_impl_.clothes_name_.IsDefault()) {
          _this->_internal_set_clothes_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_brand_name().empty()) {
        _this->_internal_set_brand_name(from._internal_brand_name());
      } else {
        if (_this->_impl_.brand_name_.IsDefault()) {
          _this->_internal_set_brand_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_purchase_link().empty()) {
        _this->_internal_set_purchase_link(from._internal_purchase_link());
      } else {
        if (_this->_impl_.purchase_link_.IsDefault()) {
          _this->_internal_set_purchase_link("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_price()) != 0) {
        _this->_impl_.price_ = from._impl_.price_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RetailResponse::CopyFrom(const RetailResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:outfit.RetailResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RetailResponse::InternalSwap(RetailResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clothes_name_, &other->_impl_.clothes_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.brand_name_, &other->_impl_.brand_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.purchase_link_, &other->_impl_.purchase_link_, arena);
  swap(_impl_.price_, other->_impl_.price_);
}

::google::protobuf::Metadata RetailResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace outfit
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_outfit_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
